version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: spinlive
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./apps/backend
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/spinlive
      - JWT_SECRET=your_jwt_secret
      - TIKTOK_USERNAME=your_tiktok_username
    depends_on:
      - db

  frontend:
    build: ./apps/frontend
    ports:
      - "4200:4200"

volumes:
  postgres_data: